//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonnenberg.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonnenberg.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error (Argument)..
        /// </summary>
        public static string argumentExceptionMessage {
            get {
                return ResourceManager.GetString("argumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clickedItemPath must not be NULL..
        /// </summary>
        public static string clickedItemPathArgumentNullException {
            get {
                return ResourceManager.GetString("clickedItemPathArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Directory Path (Unix-Style).
        /// </summary>
        public static string copyDirectoryPathText {
            get {
                return ResourceManager.GetString("copyDirectoryPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File Path (Unix-Style).
        /// </summary>
        public static string copyFilePathText {
            get {
                return ResourceManager.GetString("copyFilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Folder Path (Unix-Style).
        /// </summary>
        public static string copyFolderPathText {
            get {
                return ResourceManager.GetString("copyFolderPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Directory Path.
        /// </summary>
        public static string copyForwardslashedDirectoryPathText {
            get {
                return ResourceManager.GetString("copyForwardslashedDirectoryPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File Path.
        /// </summary>
        public static string copyForwardslashedFilePathText {
            get {
                return ResourceManager.GetString("copyForwardslashedFilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Folder Path.
        /// </summary>
        public static string copyForwardslashedFolderPathText {
            get {
                return ResourceManager.GetString("copyForwardslashedFolderPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy result to clipboard?.
        /// </summary>
        public static string copyResultToClipboard {
            get {
                return ResourceManager.GetString("copyResultToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Lines.
        /// </summary>
        public static string countAllLines {
            get {
                return ResourceManager.GetString("countAllLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Lines (w/o empty lines).
        /// </summary>
        public static string countLinesNoEmptyOnes {
            get {
                return ResourceManager.GetString("countLinesNoEmptyOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the application. Please try again, or restart Windows Explorer and try again..
        /// </summary>
        public static string failedToStartApplicationError {
            get {
                return ResourceManager.GetString("failedToStartApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop the application. Please try again, or restart Windows Explorer and try again..
        /// </summary>
        public static string failedToStopApplicationError {
            get {
                return ResourceManager.GetString("failedToStopApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: File path is too long..
        /// </summary>
        public static string filePathTooLongError {
            get {
                return ResourceManager.GetString("filePathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Image Info.
        /// </summary>
        public static string getImageInfoText {
            get {
                return ResourceManager.GetString("getImageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines.
        /// </summary>
        public static string lines {
            get {
                return ResourceManager.GetString("lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines Count.
        /// </summary>
        public static string linesCountMsgBoxTitle {
            get {
                return ResourceManager.GetString("linesCountMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Directory).
        /// </summary>
        public static string menuStripNameDirectoryMenu {
            get {
                return ResourceManager.GetString("menuStripNameDirectoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (File).
        /// </summary>
        public static string menuStripNameFileMenu {
            get {
                return ResourceManager.GetString("menuStripNameFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (File Shortcut).
        /// </summary>
        public static string menuStripNameFileShortcutMenu {
            get {
                return ResourceManager.GetString("menuStripNameFileShortcutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Folder).
        /// </summary>
        public static string menuStripNameFolderMenu {
            get {
                return ResourceManager.GetString("menuStripNameFolderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Folder Shortcut).
        /// </summary>
        public static string menuStripNameFolderShortcutMenu {
            get {
                return ResourceManager.GetString("menuStripNameFolderShortcutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: You are not authorized to acces this file..
        /// </summary>
        public static string notAuthorizedError {
            get {
                return ResourceManager.GetString("notAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bash (Admin).
        /// </summary>
        public static string openBashHereElevatedText {
            get {
                return ResourceManager.GetString("openBashHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bash.
        /// </summary>
        public static string openBashHereText {
            get {
                return ResourceManager.GetString("openBashHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bash Inside (Admin).
        /// </summary>
        public static string openBashInsideElevatedText {
            get {
                return ResourceManager.GetString("openBashInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bash Inside.
        /// </summary>
        public static string openBashInsideText {
            get {
                return ResourceManager.GetString("openBashInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CMD (Admin).
        /// </summary>
        public static string openCmdHereElevatedText {
            get {
                return ResourceManager.GetString("openCmdHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CMD.
        /// </summary>
        public static string openCmdHereText {
            get {
                return ResourceManager.GetString("openCmdHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CMD Inside (Admin).
        /// </summary>
        public static string openCmdInsideElevatedText {
            get {
                return ResourceManager.GetString("openCmdInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CMD Inside.
        /// </summary>
        public static string openCmdInsideText {
            get {
                return ResourceManager.GetString("openCmdInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Parent Folder.
        /// </summary>
        public static string openFileShortcutTargetFolderText {
            get {
                return ResourceManager.GetString("openFileShortcutTargetFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Target Folder.
        /// </summary>
        public static string openFolderShortcutTargetFolderText {
            get {
                return ResourceManager.GetString("openFolderShortcutTargetFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitBash (Admin).
        /// </summary>
        public static string openGitBashHereElevatedText {
            get {
                return ResourceManager.GetString("openGitBashHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitBash.
        /// </summary>
        public static string openGitBashHereText {
            get {
                return ResourceManager.GetString("openGitBashHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitBash Inside (Admin).
        /// </summary>
        public static string openGitBashInsideElevatedText {
            get {
                return ResourceManager.GetString("openGitBashInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitBash Inside.
        /// </summary>
        public static string openGitBashInsideText {
            get {
                return ResourceManager.GetString("openGitBashInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitCMD (Admin).
        /// </summary>
        public static string openGitCmdHereElevatedText {
            get {
                return ResourceManager.GetString("openGitCmdHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitCMD.
        /// </summary>
        public static string openGitCmdHereText {
            get {
                return ResourceManager.GetString("openGitCmdHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitCMD Inside (Admin).
        /// </summary>
        public static string openGitCmdInsideElevatedText {
            get {
                return ResourceManager.GetString("openGitCmdInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitCMD Inside.
        /// </summary>
        public static string openGitCmdInsideText {
            get {
                return ResourceManager.GetString("openGitCmdInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Git (Admin).
        /// </summary>
        public static string openGitHereElevatedText {
            get {
                return ResourceManager.GetString("openGitHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Git.
        /// </summary>
        public static string openGitHereText {
            get {
                return ResourceManager.GetString("openGitHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Git Inside (Admin).
        /// </summary>
        public static string openGitInsideElevatedText {
            get {
                return ResourceManager.GetString("openGitInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Git Inside.
        /// </summary>
        public static string openGitInsideText {
            get {
                return ResourceManager.GetString("openGitInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Powershell (Admin).
        /// </summary>
        public static string openPowershellHereElevatedText {
            get {
                return ResourceManager.GetString("openPowershellHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Powershell.
        /// </summary>
        public static string openPowershellHereText {
            get {
                return ResourceManager.GetString("openPowershellHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Powershell inside (Admin).
        /// </summary>
        public static string openPowershellInsideElevatedText {
            get {
                return ResourceManager.GetString("openPowershellInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Powershell inside.
        /// </summary>
        public static string openPowershellInsideText {
            get {
                return ResourceManager.GetString("openPowershellInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shell (Admin).
        /// </summary>
        public static string openShHereElevatedText {
            get {
                return ResourceManager.GetString("openShHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shell.
        /// </summary>
        public static string openShHereText {
            get {
                return ResourceManager.GetString("openShHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shell Inside (Admin).
        /// </summary>
        public static string openShInsideElevatedText {
            get {
                return ResourceManager.GetString("openShInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shell Inside.
        /// </summary>
        public static string openShInsideText {
            get {
                return ResourceManager.GetString("openShInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation ran out of memory (OutOfMemory)..
        /// </summary>
        public static string outOfMemoryError {
            get {
                return ResourceManager.GetString("outOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation ran out of memory (OutOfMemory)..
        /// </summary>
        public static string outOfMemoryExceptionMessage {
            get {
                return ResourceManager.GetString("outOfMemoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file..
        /// </summary>
        public static string readFileError {
            get {
                return ResourceManager.GetString("readFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to determine the current Windows Theme..
        /// </summary>
        public static string readWindowsThemeRegKeyFailed {
            get {
                return ResourceManager.GetString("readWindowsThemeRegKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: The service has started..
        /// </summary>
        public static string serviceStarted {
            get {
                return ResourceManager.GetString("serviceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: The service is running..
        /// </summary>
        public static string serviceStartedAlready {
            get {
                return ResourceManager.GetString("serviceStartedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: The service has stopped..
        /// </summary>
        public static string serviceStopped {
            get {
                return ResourceManager.GetString("serviceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: The service is not running..
        /// </summary>
        public static string serviceStoppedAlready {
            get {
                return ResourceManager.GetString("serviceStoppedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to provide an agrument..
        /// </summary>
        public static string shellserverArgumentMissingError {
            get {
                return ResourceManager.GetString("shellserverArgumentMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold not start the server..
        /// </summary>
        public static string startServerFail {
            get {
                return ResourceManager.GetString("startServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the application. Please try again, or restart Windows Explorer and try again..
        /// </summary>
        public static string startServiceError {
            get {
                return ResourceManager.GetString("startServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Sonnenberg Service..
        /// </summary>
        public static string startServiceFail {
            get {
                return ResourceManager.GetString("startServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully started Sonnenberg Service..
        /// </summary>
        public static string startServiceSuccess {
            get {
                return ResourceManager.GetString("startServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold not stop the server..
        /// </summary>
        public static string stopServerFail {
            get {
                return ResourceManager.GetString("stopServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop the application. Please try again, or restart Windows Explorer and try again..
        /// </summary>
        public static string stopServiceError {
            get {
                return ResourceManager.GetString("stopServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stopSonnenberg Service..
        /// </summary>
        public static string stopServiceFail {
            get {
                return ResourceManager.GetString("stopServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully stoppedSonnenberg Service..
        /// </summary>
        public static string stopServiceSuccess {
            get {
                return ResourceManager.GetString("stopServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
