//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonnenberg.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonnenberg.Language.Strings.de", typeof(Strings_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler (Argument)..
        /// </summary>
        public static string argumentExceptionMessage {
            get {
                return ResourceManager.GetString("argumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clickedItemPath darf nicht NULL sein..
        /// </summary>
        public static string clickedItemPathArgumentNullException {
            get {
                return ResourceManager.GetString("clickedItemPathArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis-Pfad kopieren (Unix-Style).
        /// </summary>
        public static string copyDirectoryPathText {
            get {
                return ResourceManager.GetString("copyDirectoryPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei-Pfad kopieren (Unix-Style).
        /// </summary>
        public static string copyFilePathText {
            get {
                return ResourceManager.GetString("copyFilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner-Pfad kopieren (Unix-Style).
        /// </summary>
        public static string copyFolderPathText {
            get {
                return ResourceManager.GetString("copyFolderPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis-Pfad kopieren.
        /// </summary>
        public static string copyForwardslashedDirectoryPathText {
            get {
                return ResourceManager.GetString("copyForwardslashedDirectoryPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei-Pfad kopieren.
        /// </summary>
        public static string copyForwardslashedFilePathText {
            get {
                return ResourceManager.GetString("copyForwardslashedFilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner-Pfad kopieren.
        /// </summary>
        public static string copyForwardslashedFolderPathText {
            get {
                return ResourceManager.GetString("copyForwardslashedFolderPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultat in die Zwischenablage kopieren?.
        /// </summary>
        public static string copyResultToClipboard {
            get {
                return ResourceManager.GetString("copyResultToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeilen zählen.
        /// </summary>
        public static string countAllLines {
            get {
                return ResourceManager.GetString("countAllLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeilen zählen (ohne Leerzeilen).
        /// </summary>
        public static string countLinesNoEmptyOnes {
            get {
                return ResourceManager.GetString("countLinesNoEmptyOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte die Anwendung nicht starten. Starten Sie bitte Windows Explorer neu und versuchen Sie es erneut..
        /// </summary>
        public static string failedToStartApplicationError {
            get {
                return ResourceManager.GetString("failedToStartApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte die Anwendung nicht stoppen. Starten Sie bitte Windows Explorer neu und versuchen Sie es erneut..
        /// </summary>
        public static string failedToStopApplicationError {
            get {
                return ResourceManager.GetString("failedToStopApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateiname.
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Der Datei-Pfad ist zu lang..
        /// </summary>
        public static string filePathTooLongError {
            get {
                return ResourceManager.GetString("filePathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild-Informationen anzeigen.
        /// </summary>
        public static string getImageInfoText {
            get {
                return ResourceManager.GetString("getImageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höhe.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeilen.
        /// </summary>
        public static string lines {
            get {
                return ResourceManager.GetString("lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Zeilen.
        /// </summary>
        public static string linesCountMsgBoxTitle {
            get {
                return ResourceManager.GetString("linesCountMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Verzeichnis).
        /// </summary>
        public static string menuStripNameDirectoryMenu {
            get {
                return ResourceManager.GetString("menuStripNameDirectoryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Datei).
        /// </summary>
        public static string menuStripNameFileMenu {
            get {
                return ResourceManager.GetString("menuStripNameFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Datei-Verknüpfung).
        /// </summary>
        public static string menuStripNameFileShortcutMenu {
            get {
                return ResourceManager.GetString("menuStripNameFileShortcutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Ordner).
        /// </summary>
        public static string menuStripNameFolderMenu {
            get {
                return ResourceManager.GetString("menuStripNameFolderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg (Ordner-Verknüpfung).
        /// </summary>
        public static string menuStripNameFolderShortcutMenu {
            get {
                return ResourceManager.GetString("menuStripNameFolderShortcutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler: Sie verfügen nicht über die erforderlichen Zugriffs-Berechtigungen für die Datei..
        /// </summary>
        public static string notAuthorizedError {
            get {
                return ResourceManager.GetString("notAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash öffnen (Admin).
        /// </summary>
        public static string openBashHereElevatedText {
            get {
                return ResourceManager.GetString("openBashHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash öffnen.
        /// </summary>
        public static string openBashHereText {
            get {
                return ResourceManager.GetString("openBashHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash innerhalb öffnen (Admin).
        /// </summary>
        public static string openBashInsideElevatedText {
            get {
                return ResourceManager.GetString("openBashInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bash innerhalb öffnen.
        /// </summary>
        public static string openBashInsideText {
            get {
                return ResourceManager.GetString("openBashInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsole öffnen (Admin).
        /// </summary>
        public static string openCmdHereElevatedText {
            get {
                return ResourceManager.GetString("openCmdHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsole öffnen.
        /// </summary>
        public static string openCmdHereText {
            get {
                return ResourceManager.GetString("openCmdHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsole innerhalb öffnen (Admin).
        /// </summary>
        public static string openCmdInsideElevatedText {
            get {
                return ResourceManager.GetString("openCmdInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsole innerhalb öffnen.
        /// </summary>
        public static string openCmdInsideText {
            get {
                return ResourceManager.GetString("openCmdInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übergeordneten Ordner öffnen.
        /// </summary>
        public static string openFileShortcutTargetFolderText {
            get {
                return ResourceManager.GetString("openFileShortcutTargetFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zielverzeichnis öffnen.
        /// </summary>
        public static string openFolderShortcutTargetFolderText {
            get {
                return ResourceManager.GetString("openFolderShortcutTargetFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitBash öffnen (Admin).
        /// </summary>
        public static string openGitBashHereElevatedText {
            get {
                return ResourceManager.GetString("openGitBashHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitBash öffnen.
        /// </summary>
        public static string openGitBashHereText {
            get {
                return ResourceManager.GetString("openGitBashHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitBash innerhalb öffnen (Admin).
        /// </summary>
        public static string openGitBashInsideElevatedText {
            get {
                return ResourceManager.GetString("openGitBashInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitBash innerhalb öffnen.
        /// </summary>
        public static string openGitBashInsideText {
            get {
                return ResourceManager.GetString("openGitBashInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitCMD öffnen (Admin).
        /// </summary>
        public static string openGitCmdHereElevatedText {
            get {
                return ResourceManager.GetString("openGitCmdHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitCMD öffnen.
        /// </summary>
        public static string openGitCmdHereText {
            get {
                return ResourceManager.GetString("openGitCmdHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitCMD innerhalb öffnen (Admin).
        /// </summary>
        public static string openGitCmdInsideElevatedText {
            get {
                return ResourceManager.GetString("openGitCmdInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitCMD innerhalb öffnen.
        /// </summary>
        public static string openGitCmdInsideText {
            get {
                return ResourceManager.GetString("openGitCmdInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git öffnen (Admin).
        /// </summary>
        public static string openGitHereElevatedText {
            get {
                return ResourceManager.GetString("openGitHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git öffnen.
        /// </summary>
        public static string openGitHereText {
            get {
                return ResourceManager.GetString("openGitHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git innerhalb öffnen (Admin).
        /// </summary>
        public static string openGitInsideElevatedText {
            get {
                return ResourceManager.GetString("openGitInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git innerhalb öffnen.
        /// </summary>
        public static string openGitInsideText {
            get {
                return ResourceManager.GetString("openGitInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell öffnen (Admin).
        /// </summary>
        public static string openPowershellHereElevatedText {
            get {
                return ResourceManager.GetString("openPowershellHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell öffnen.
        /// </summary>
        public static string openPowershellHereText {
            get {
                return ResourceManager.GetString("openPowershellHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell innerhalb öffnen (Admin).
        /// </summary>
        public static string openPowershellInsideElevatedText {
            get {
                return ResourceManager.GetString("openPowershellInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell innerhalb öffnen.
        /// </summary>
        public static string openPowershellInsideText {
            get {
                return ResourceManager.GetString("openPowershellInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell öffnen (Admin).
        /// </summary>
        public static string openShHereElevatedText {
            get {
                return ResourceManager.GetString("openShHereElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell öffnen.
        /// </summary>
        public static string openShHereText {
            get {
                return ResourceManager.GetString("openShHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell innerhalb öffnen (Admin).
        /// </summary>
        public static string openShInsideElevatedText {
            get {
                return ResourceManager.GetString("openShInsideElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell innerhalb öffnen.
        /// </summary>
        public static string openShInsideText {
            get {
                return ResourceManager.GetString("openShInsideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuwenig Speicher vorhanden, um die Operation auszuführen..
        /// </summary>
        public static string outOfMemoryError {
            get {
                return ResourceManager.GetString("outOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ie Operation auszuführen..
        /// </summary>
        public static string outOfMemoryExceptionMessage {
            get {
                return ResourceManager.GetString("outOfMemoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte die Datei nicht lesen..
        /// </summary>
        public static string readFileError {
            get {
                return ResourceManager.GetString("readFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte das gegenwärtige Windows-Theme nicht ermitteln..
        /// </summary>
        public static string readWindowsThemeRegKeyFailed {
            get {
                return ResourceManager.GetString("readWindowsThemeRegKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Der Dienst wurde gestartet..
        /// </summary>
        public static string serviceStarted {
            get {
                return ResourceManager.GetString("serviceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Der Dienst läuft bereits..
        /// </summary>
        public static string serviceStartedAlready {
            get {
                return ResourceManager.GetString("serviceStartedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Der Dienst wurde angehalten..
        /// </summary>
        public static string serviceStopped {
            get {
                return ResourceManager.GetString("serviceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Der Dienst ist gestoppt..
        /// </summary>
        public static string serviceStoppedAlready {
            get {
                return ResourceManager.GetString("serviceStoppedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen ein Argument mit übergeben..
        /// </summary>
        public static string shellserverArgumentMissingError {
            get {
                return ResourceManager.GetString("shellserverArgumentMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Shell-ServerKonnte den Dienst nicht starten..
        /// </summary>
        public static string startServerFail {
            get {
                return ResourceManager.GetString("startServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Konnte den Dienst nicht starten..
        /// </summary>
        public static string startServiceError {
            get {
                return ResourceManager.GetString("startServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Konnte den Dienst nicht starten..
        /// </summary>
        public static string startServiceFail {
            get {
                return ResourceManager.GetString("startServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Dienst erfolgreich gestartet..
        /// </summary>
        public static string startServiceSuccess {
            get {
                return ResourceManager.GetString("startServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Shell-ServerKonnte den Dienst nicht stoppen..
        /// </summary>
        public static string stopServerFail {
            get {
                return ResourceManager.GetString("stopServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Konnte den Dienst nicht stoppen..
        /// </summary>
        public static string stopServiceError {
            get {
                return ResourceManager.GetString("stopServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Konnte den Dienst nicht stoppen..
        /// </summary>
        public static string stopServiceFail {
            get {
                return ResourceManager.GetString("stopServiceFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonnenberg Service: Dienst erfolgreich angehalten..
        /// </summary>
        public static string stopServiceSuccess {
            get {
                return ResourceManager.GetString("stopServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breite.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
